# Generated by Django 2.1.7 on 2019-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_name', models.CharField(help_text='Name of the Bill (Office Rent, Electricity Bill, etc.)', max_length=300)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('bill_due_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
