# Generated by Django 2.1.7 on 2019-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_due_date',
            field=models.DateField(default=None),
        ),
    ]
