# Generated by Django 2.1.7 on 2019-05-02 03:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20190429_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_mail_to',
            field=models.EmailField(default='sachinbisht939@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_due_date',
            field=models.IntegerField(help_text='Enter date b/w 1 and 28', validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)]),
        ),
    ]
