# Generated by Django 2.1.7 on 2019-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20190505_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
